### PR TITLE
CDC driver workaround + websocket server?

### LINKED ISSUE #2: USB serial device not found
CDC device works when I use this app: https://play.google.com/store/apps/details?id=de.kai_morich.serial_usb_terminal&hl=en_US&gl=US

### PR DESCRIPTION
**Pull request by brandonros**
attempts to fix https://github.com/ClusterM/usb-serial-telnet-server/issues/2

### CODE REVIEW

**Comment by brandonros** [comment]
I doubt you want this. If you are looking to collabrate, let me know. I'm working on a WebUSB workaround since the Android Linux kernel grabs the USB device for the cdc_adm driver and there's no known way at the moment to detach it.

Great project. Really good code. Appreciate it.

**Comment by ClusterM** [comment]
I have not tested it yet. If you're done with your branch, i'll test and merge it.

**Comment by brandonros** [comment]
Do you think it's worth it to add it as a setting? telnet or WebSocket?

I ran into an issue where you can't use a ws:// (http://) WebSocket in an https:// context.

Given that, I don't know how much value this has. I have a working fork now with USB -> JavaScript IPC for a WebView but it's very gross/hacked because I've done very little (none) Android app development before.

**Comment by ClusterM** [comment]
I don't know. Not sure.

**Pull request closed without merging**
